### ISSUE TITLE
Unable to delete primary packaged folder

### ISSUE THREAD

**Issue by derrydchen** [ReproNim/brainverse#23]
- On mac, authentication required to delete created package folder, and even then, does not delete folder
- ADVISORY WARNING: Only way to delete so far is in console: rm -rf <Folder>

**Comment by satra** [comment]
@derry0822 - perhaps check to see how the app can be installed in user space (without requiring any root privileges).

**Comment by smpadhy** [comment]
@satra when the electron packager  is run, it creates a new folder within the brainverse development directory with all app executables. This new folder can be zipped and distributed. The app can be installed (technically involves unzipping and clicking on the app executable) anywhere in userspace. No root privilege is required. It is when @derry0822  tries to delete the new folder created within brainverse development folder with app executables, he is not able to do so because of permission issues.

**Comment by smpadhy** [comment]
The default installation of nodejs and npm in OSX makes user install any global package using sudo privilege. This what happened when we install electron-packager globally.
Here is the instruction http://www.filtercode.com/devops/npm-global-without-sudo to change the nodejs and npm installation

**Comment by smpadhy** [comment]
We are using electron-builder to build electron app.
